#!/usr/bin/env python

from embodied_ising import ising,KL
import numpy as np
import matplotlib.pyplot as plt
from infoflow import MI,TE,Entropy



#Define number of units of agent, environment, sensors and motors

envsize=1
nmotors=1
nsensors=1
nhidden=0
agentsize=nmotors+nsensors+nhidden
sensors=np.arange(0,nsensors)
motors=np.arange(nsensors+nhidden,agentsize)
size=agentsize+envsize

x=ising(agentsize,envsize,sensors,motors)

#Set parameters to random values
C=1.5
Amp=C
Cin=C
Cout=C
offset=0.8

x.random_fields(mode='environment',std=1)
x.random_wiring(mode='environment',std=Amp/float(envsize),offset=offset)
x.random_wiring(mode='sensors',std=Cin/float(envsize),offset=offset)
x.random_wiring(mode='motors',std=Cout/float(len(motors)),offset=offset)

x.random_fields(mode='agent',std=0.1)
x.random_wiring(mode='agent',std=0.1)

#x.h[1]=np.random.randn(1)*0.1
#x.J[0,1]=np.random.randn(1)*0.01
#x.h[2]=-1
#x.J[0,2]=1.5
#x.J[1,2]=1.5


xc=ising(agentsize,envsize,sensors,motors)
xc.h=x.h.copy()
xc.J=x.J.copy()


J0=xc.J.copy()
plt.figure()
plt.imshow(J0,interpolation='nearest')
plt.title('J initial')
plt.colorbar()

		
#Execute learning algorithm
T=100
Iterations=100
x.BoltzmannLearning(Iterations,T)
xc.CriticalLearning(Iterations,T,mode='dynamic')


print(x.h)
print(xc.h)
#Show results
plt.figure()
plt.imshow(x.J[0:x.Asize,0:x.Asize],interpolation='nearest')
plt.title('J predictive')
plt.colorbar()

plt.figure()
plt.imshow(xc.J[0:xc.Asize,0:xc.Asize],interpolation='nearest')
plt.title('J critical')
plt.colorbar()

T=10000
M=np.zeros(T)
S=np.zeros(T)
E=np.zeros(T)
P=np.zeros(2**xc.size)

x.randomize_state()
t=0
while t<T:
	for i in np.random.permutation(x.size):
		if t<T:
			x.Update(i)
			M[t]=x.get_agent_state_index('motors')
			S[t]=x.get_agent_state_index('sensors')
			E[t]=x.get_agent_state_index('environment')
			n=x.get_agent_state_index()
			P[n]+=1
			t+=1

	
A=S+2**nsensors*M
P/=float(np.sum(P))
	
Mc=np.zeros(T)
Sc=np.zeros(T)
Ec=np.zeros(T)
Pc=np.zeros(2**xc.size)

xc.randomize_state()
t=0
while t<T:
	for i in np.random.permutation(xc.size):
		if t<T:
			xc.Update(i)
			Mc[t]=xc.get_agent_state_index('motors')
			Sc[t]=xc.get_agent_state_index('sensors')
			Ec[t]=xc.get_agent_state_index('environment')
			n=xc.get_agent_state_index()
			Pc[n]+=1
			t+=1
		
Ac=Sc+2**nsensors*Mc
Pc/=float(np.sum(Pc))

order=np.argsort(P)[::-1]
r=np.arange(1,2**x.size+1)
plt.figure()
plt.loglog(r,P[order])


order=np.argsort(Pc)[::-1]
r=np.arange(1,2**xc.size+1)
plt.loglog(r,Pc[order],'r')
Psf = 1.0/(1+np.arange(2**size))
Psf/=np.sum(Psf)
plt.loglog(r,Psf,'--g')

#plt.show()
#exit()

plt.figure()
plt.plot(M)
plt.plot(S)

plt.figure()
plt.plot(Mc)
plt.plot(Sc)

print('Predictive')
print('EntropyM',Entropy(M),'EntropyS',Entropy(S))
print('MIsm',MI(M,S))
print('MIae',MI(S+M*2**nsensors,E))

rs=np.unique(np.round(2**np.arange(0,7.5,0.25)).astype(int))
TEms=np.zeros(len(rs))
TEsm=np.zeros(len(rs))
for i,r in enumerate(rs):
	TEms[i]=TE(M,S,r)
	TEsm[i]=TE(S,M,r)
print('mean TEms',np.mean(TEms))
print('mean TEsm',np.mean(TEsm))

print
print('Critical')
print('EntropyM',Entropy(Mc),'EntropyS',Entropy(Sc))
print('MIsm',MI(Mc,Sc))
print('MIae',MI(Sc+Mc*2**nsensors,Ec))


plt.figure()
plt.semilogx(rs,TEms,'--r',linewidth=1.5,label='m->s (predictive)')
plt.semilogx(rs,TEsm,'--b',linewidth=1.5,label='s->m (predictive)')


TEmsc=np.zeros(len(rs))
TEsmc=np.zeros(len(rs))
for i,r in enumerate(rs):
	TEmsc[i]=TE(Mc,Sc,r)
	TEsmc[i]=TE(Sc,Mc,r)
	
	
print('mean TEms',np.mean(TEmsc))
print('mean TEsm',np.mean(TEsmc))

plt.semilogx(rs,TEmsc,'r',linewidth=1.5,label='m->s (critical)')
plt.semilogx(rs,TEsmc,'b',linewidth=1.5,label='s->m (critical)')
plt.title('Transfer entropy sensors-motors')
plt.legend()





x.observables_positive(200)
x.observables_negative(200)
fit = KL(x.PVpos,x.PVneg)
print(fit)

xc.observables_positive(200)
xc.observables_negative(200)
fit = KL(xc.PVpos,xc.PVneg)
print(fit)

plt.show()
